/*
 * uds_service.c
 * Master Service Dispatch (UDS Request Router) — Implementation
 *
 * Central dispatch engine for all UDS service handlers.  Maintains a
 * static dispatch table with session-aware routing, supports handler
 * registration, and applies functional-addressing NRC suppression per
 * ISO 14229-1 Tables 4-7.
 *
 * Wave 3d Task 18 — Master Service Dispatch (UDS Request Router)
 */

#include "uds/uds_service.h"
#include "uds/uds_svc_diagcomm.h"
#include "uds/uds_svc_data.h"
#include "uds/uds_svc_stored.h"
#include "uds/uds_svc_io.h"
#include "uds/uds_svc_routine.h"
#include "uds/uds_svc_upload.h"
#include "uds/uds_svc_auth.h"
#include <stddef.h>   /* NULL */

/* ======================================================================== *
 * Static Dispatch Table                                                     *
 * ======================================================================== */

/** @brief Static array of registered service entries */
static uds_service_entry_t g_service_table[UDS_SERVICE_TABLE_MAX];

/* ======================================================================== *
 * Static NRC Response Buffer                                                *
 * ======================================================================== *
 * Used exclusively for negative responses generated by the dispatch itself
 * (not by individual service handlers).  Safe because dispatch is called
 * sequentially in a single-threaded environment.
 */

static uint8_t g_nrc_buf[1];

/* ======================================================================== *
 * Stub Handlers for Services without a dedicated implementation            *
 * ======================================================================== */

/**
 * @brief Stub handler for 0x84 — SecuredDataTransmission.
 *
 * Returns NRC 0x33 (securityAccessDenied) per implementation policy.
 * Secured data transmission requires additional security credentials
 * that are not available in this implementation.
 */
static bool secured_data_stub(const uds_request_t *req,
                              uds_response_t      *rsp,
                              void                *context)
{
    (void)context;

    rsp->sid          = 0x7F;
    rsp->subfunc_echo = req->sid;
    g_nrc_buf[0]      = NRC_SECURITY_ACCESS_DENIED;
    rsp->data         = g_nrc_buf;
    rsp->data_len     = 1;
    return true;
}

/* ======================================================================== *
 * Dispatch Engine                                                           *
 * ======================================================================== */

bool uds_service_register(uint8_t sid, uds_service_handler_t handler, uint8_t session_mask)
{
    if (handler == NULL)
        return false;

    /* Check for duplicate SID and find first free slot */
    bool found_slot = false;
    uint8_t slot = 0;

    for (uint8_t i = 0; i < UDS_SERVICE_TABLE_MAX; i++)
    {
        if (g_service_table[i].active && g_service_table[i].sid == sid)
            return false;  /* Duplicate SID */

        if (!found_slot && !g_service_table[i].active)
        {
            slot = i;
            found_slot = true;
        }
    }

    if (!found_slot)
        return false;  /* Table full */

    /* Register the entry */
    g_service_table[slot].sid          = sid;
    g_service_table[slot].handler      = handler;
    g_service_table[slot].session_mask = session_mask;
    g_service_table[slot].active       = true;

    return true;
}

bool uds_service_dispatch(const uds_request_t *req,
                          uds_response_t      *rsp,
                          uint8_t              current_session,
                          uds_addressing_t     ta_type,
                          void                *context)
{
    /* ---- Input validation ---- */
    if (req == NULL || rsp == NULL)
        return false;

    /* ---- SID lookup ---- */
    const uds_service_entry_t *entry = uds_service_find(req->sid);

    if (entry == NULL || !entry->active)
    {
        /*
         * Service not supported.
         * Per ISO 14229-1 Table 4: for functional addressing, NRC 0x11
         * shall not be sent — silently suppress the response.
         */
        if (ta_type == UDS_FUNCTIONAL)
            return false;

        /* Physical addressing: return NRC 0x11 */
        rsp->sid          = 0x7F;
        rsp->subfunc_echo = req->sid;
        g_nrc_buf[0]      = NRC_SERVICE_NOT_SUPPORTED;
        rsp->data         = g_nrc_buf;
        rsp->data_len     = 1;
        return true;
    }

    /* ---- Session availability check ---- */
    /*
     * session_mask uses bits 0-2 for default/programming/extended.
     * current_session values are 0x01, 0x02, 0x03.
     * Mapping: bit = (current_session - 1)
     */
    {
        uint8_t session_bit = (uint8_t)(1u << (current_session - 1u));
        if ((entry->session_mask & session_bit) == 0u)
        {
            /* Service not supported in active session — NRC 0x7F */
            rsp->sid          = 0x7F;
            rsp->subfunc_echo = req->sid;
            g_nrc_buf[0]      = NRC_SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION;
            rsp->data         = g_nrc_buf;
            rsp->data_len     = 1;
            return true;
        }
    }

    /* ---- Delegate to the registered handler ---- */
    bool send_response = entry->handler(req, rsp, context);

    /*
     * ---- Apply functional-addressing NRC suppression ----
     * Per ISO 14229-1 Tables 4-7: the following NRCs shall not be sent
     * when the request was received via functional addressing:
     *   - 0x11 (serviceNotSupported)
     *   - 0x12 (subFunctionNotSupported)
     *   - 0x31 (requestOutOfRange)
     *
     * If the handler returned a negative response with one of these NRCs
     * and the request was functional, suppress the response entirely.
     */
    if (send_response && ta_type == UDS_FUNCTIONAL)
    {
        /* Check if the response is negative (indicated by SID == 0x7F) */
        if (rsp->sid == 0x7F && rsp->data != NULL && rsp->data_len >= 1)
        {
            uint8_t nrc = rsp->data[0];
            if (nrc == NRC_SERVICE_NOT_SUPPORTED                ||
                nrc == NRC_SUB_FUNCTION_NOT_SUPPORTED           ||
                nrc == NRC_REQUEST_OUT_OF_RANGE)
            {
                send_response = false;
            }
        }
    }

    return send_response;
}

void uds_service_init(void)
{
    /* Clear the table */
    for (uint8_t i = 0; i < UDS_SERVICE_TABLE_MAX; i++)
    {
        g_service_table[i].handler      = NULL;
        g_service_table[i].active       = false;
    }

    /*
     * ================================================================
     * Diagnostic & Communication Management Services  (Task 9)
     *   SIDs: 0x10, 0x11, 0x27, 0x28, 0x3E, 0x85, 0x86, 0x87
     * ================================================================
     */
    (void)uds_service_register(DIAGNOSTIC_SESSION_CONTROL,    uds_svc_diagnostic_session_control,    UDS_SESSION_ALL);
    (void)uds_service_register(ECU_RESET,                     uds_svc_ecu_reset,                     UDS_SESSION_ALL);
    (void)uds_service_register(SECURITY_ACCESS,               uds_svc_security_access,               UDS_SESSION_ALL);
    (void)uds_service_register(COMMUNICATION_CONTROL,         uds_svc_communication_control,         UDS_SESSION_ALL);
    (void)uds_service_register(TESTER_PRESENT,                uds_svc_tester_present,                UDS_SESSION_ALL);
    (void)uds_service_register(CONTROL_DTC_SETTING,           uds_svc_control_dtc_setting,           UDS_SESSION_NON_DEFAULT);
    (void)uds_service_register(RESPONSE_ON_EVENT,             uds_svc_response_on_event,             UDS_SESSION_NON_DEFAULT);
    (void)uds_service_register(LINK_CONTROL,                  uds_svc_link_control,                  UDS_SESSION_NON_DEFAULT);

    /*
     * ================================================================
     * Data Transmission Services  (Task 10)
     *   SIDs: 0x22, 0x23, 0x24, 0x2A, 0x2C, 0x2E, 0x3D
     * ================================================================
     */
    (void)uds_service_register(READ_DATA_BY_IDENTIFIER,       uds_svc_read_data_by_id,               UDS_SESSION_ALL);
    (void)uds_service_register(READ_MEMORY_BY_ADDRESS,        uds_svc_read_memory_by_address,        UDS_SESSION_NON_DEFAULT);
    (void)uds_service_register(READ_SCALING_DATA_BY_ID,       uds_svc_read_scaling_data_by_id,       UDS_SESSION_ALL);
    (void)uds_service_register(READ_DATA_BY_PERIODIC_ID,      uds_svc_read_data_by_periodic_id,      UDS_SESSION_ALL);
    (void)uds_service_register(DYNAMICALLY_DEFINE_DATA_ID,    uds_svc_dynamically_define_data_id,    UDS_SESSION_NON_DEFAULT);
    (void)uds_service_register(WRITE_DATA_BY_IDENTIFIER,      uds_svc_write_data_by_id,              UDS_SESSION_NON_DEFAULT);
    (void)uds_service_register(WRITE_MEMORY_BY_ADDRESS,       uds_svc_write_memory_by_address,       UDS_SESSION_NON_DEFAULT);

    /*
     * ================================================================
     * Stored Data Services  (Task 11)
     *   SIDs: 0x14, 0x19
     * ================================================================
     */
    (void)uds_service_register(CLEAR_DIAGNOSTIC_INFO,         uds_svc_clear_diagnostic_info,         UDS_SESSION_NON_DEFAULT);
    (void)uds_service_register(READ_DTC_INFO,                 uds_svc_read_dtc_info,                 UDS_SESSION_ALL);

    /*
     * ================================================================
     * IO Control Service  (Task 12)
     *   SID: 0x2F
     * ================================================================
     */
    (void)uds_service_register(INPUT_OUTPUT_CONTROL_BY_ID,    uds_svc_io_control,                    UDS_SESSION_NON_DEFAULT);

    /*
     * ================================================================
     * Routine Control Service  (Task 13)
     *   SID: 0x31
     * ================================================================
     */
    (void)uds_service_register(ROUTINE_CONTROL,               uds_svc_routine_control,               UDS_SESSION_ALL);

    /*
     * ================================================================
     * Upload / Download Services  (Task 14)
     *   SIDs: 0x34, 0x35, 0x36, 0x37, 0x38
     * ================================================================
     */
    (void)uds_service_register(REQUEST_DOWNLOAD,              uds_svc_request_download,              UDS_SESSION_PROGRAMMING);
    (void)uds_service_register(REQUEST_UPLOAD,                uds_svc_request_upload,                UDS_SESSION_PROGRAMMING);
    (void)uds_service_register(TRANSFER_DATA,                 uds_svc_transfer_data,                 UDS_SESSION_PROGRAMMING);
    (void)uds_service_register(REQUEST_TRANSFER_EXIT,         uds_svc_request_transfer_exit,         UDS_SESSION_PROGRAMMING);
    (void)uds_service_register(REQUEST_FILE_TRANSFER,         uds_svc_request_file_transfer,         UDS_SESSION_PROGRAMMING);

    /*
     * ================================================================
     * Authentication Service  (Task 19)
     *   SID: 0x29
     * ================================================================
     */
    (void)uds_service_register(AUTHENTICATION,                uds_svc_authentication,                UDS_SESSION_NON_DEFAULT);

    /*
     * ================================================================
     * Secured Data Transmission  (stub returning NRC 0x33)
     *   SID: 0x84
     * ================================================================
     */
    (void)uds_service_register(SECURED_DATA_TRANSMISSION,     secured_data_stub,                     UDS_SESSION_ALL);
}

uint8_t uds_service_get_count(void)
{
    uint8_t count = 0;
    for (uint8_t i = 0; i < UDS_SERVICE_TABLE_MAX; i++)
    {
        if (g_service_table[i].active)
            count++;
    }
    return count;
}

const uds_service_entry_t* uds_service_find(uint8_t sid)
{
    for (uint8_t i = 0; i < UDS_SERVICE_TABLE_MAX; i++)
    {
        if (g_service_table[i].active && g_service_table[i].sid == sid)
            return &g_service_table[i];
    }
    return NULL;
}

void uds_service_clear(void)
{
    for (uint8_t i = 0; i < UDS_SERVICE_TABLE_MAX; i++)
    {
        g_service_table[i].handler      = NULL;
        g_service_table[i].active       = false;
    }
}
